services:
  stltexturizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stltexturizer
    restart: unless-stopped
    ports:
      - "8083:3000"
    volumes:
      - /mnt/raid1/stltexturizer/data:/data
